// Every piece of UI copy lives here, so a second language can be added without touching components.
// Hebrew only for now (see PRODUCT.md). Copy follows the approved frames 6a–6h and 7a–7n.

const monthNames = ["ינואר", "פברואר", "מרץ", "אפריל", "מאי", "יוני", "יולי", "אוגוסט", "ספטמבר", "אוקטובר", "נובמבר", "דצמבר"];

export const t = {
  appName: "הכסף שלנו",
  monthName: (month: string) => monthNames[Number(month.slice(5, 7)) - 1],
  monthLabel: (month: string) => `${monthNames[Number(month.slice(5, 7)) - 1]} ${month.slice(0, 4)}`,
  prevMonth: "החודש הקודם",
  nextMonth: "החודש הבא",

  greeting: (names: string[]) => (names.length ? `היי ${names.join(" ו")}` : "היי"),
  heroQuestion: (month: string) => `איך צפוי להסתיים השוטף של ${t.monthName(month)}?`,
  projectHeroQuestion: (month: string) => `איך צפוי להסתיים הפרויקט ב${t.monthName(month)}?`,

  variable: "הוצאות משתנות",
  fixed: "הוצאות קבועות",
  income: "הכנסות",
  notInCashflow: "לא בתזרים",
  notInCashflowDetail: "פירוט הוצאות לא תזרימיות",
  spent: "יצא",
  expectedOut: "צפוי לצאת",
  wasExpectedOut: "צפוי היה לצאת",
  recommendedUpTo: "מומלץ להוציא עד",
  received: "נכנס",
  expectedIn: "צפוי להיכנס",
  leftToSpend: (amount: string) => `נשאר להוציא ${amount}`,
  overspend: (amount: string) => `חריגה של ${amount}!`,
  moreExpectedIn: (amount: string) => `עוד ${amount} צפויים להיכנס`,
  weeklyDetail: "פירוט שבועי",
  monthlyDetail: "פירוט חודשי",
  incomeDetail: "פירוט הכנסות",
  noItems: "אין תנועות החודש",

  summaryTitle: (month: string) => `סיכום ${t.monthName(month)}`,
  summarySub: "צפי לסוף החודש",
  ongoing: "שוטף",
  total: "סה״כ",

  moveToProject: "להעביר לפרויקט",
  reassign: "לשייך מחדש",
  ongoingExpense: "הוצאה בשוטף",
  ongoingIncome: "הכנסה בשוטף",
  projectItem: (project: string) => `בפרויקט · ${project}`,
  whichProject: "לאיזה פרויקט להעביר?",
  newProject: "+ פרויקט חדש",
  newProjectName: "שם הפרויקט",
  moveNote: (category: string) => `התנועה תצא מהשוטף ותופיע רק בפרויקט, בקטגוריה "${category}". אפשר לשנות את הקטגוריה בתוך הפרויקט.`,
  save: "שמירה",
  cancel: "ביטול",
  movedToast: (project: string) => `התנועה עברה לפרויקט ${project}`,
  alwaysAssignQ: (merchant: string) => `לשייך תמיד את התנועות מ${merchant} לפרויקט?`,
  alwaysAssignHelp: (merchant: string) => `מעכשיו, כל תנועה חדשה מ${merchant} תעבור לפרויקט כל עוד הוא פעיל.`,
  yesAlways: "כן, תמיד",
  justThisTime: "רק הפעם",

  whichCategory: "לאיזו קטגוריה בפרויקט?",
  newCategory: "+ קטגוריה חדשה",
  moveToOtherProject: "להעביר לפרויקט אחר",
  returnToOngoing: "להחזיר לשוטף",
  returnedToast: "התנועה חזרה לשוטף",
  expenses: "הוצאות",
  expectedExpenses: "הוצאות צפויות",
  expectedIncome: "הכנסות צפויות",
  itemsCount: (n: number, income: boolean) => `${n} ${income ? "הכנסות" : "הוצאות"}`,
  addCategory: "+ הוספת קטגוריה לפרויקט",
  categoryMenu: "עריכת הסכום הצפוי",
  planQuestion: (category: string, month: string, income: boolean) =>
    `כמה כסף צפוי ${income ? "להיכנס" : "לצאת"} על ${category} ב${t.monthName(month)}?`,
  spentSoFar: (amount: string) => `יצא עד עכשיו: ${amount}`,
  updatePlan: "עדכון הסכום הצפוי",
  newCategoryTitle: "קטגוריה חדשה בפרויקט",
  categoryName: "שם הקטגוריה",
  kind: "סוג",
  expense: "הוצאה",
  incomeKind: "הכנסה",
  expectedThisMonth: (month: string, income: boolean) => `כמה צפוי ${income ? "להיכנס" : "לצאת"} ב${t.monthName(month)}?`,
  addCategoryButton: "הוספת קטגוריה",
  back: "חזרה",

  welcomeBack: "היי, טוב לראות אותך!",
  welcome: "היי, ברוכים הבאים!",
  inviteSub: "הוזמנת לנהל יחד את התזרים המשפחתי.\nנשאר רק להגדיר כניסה מהטלפון הזה.",
  yourName: "איך קוראים לך?",
  nameHelp: "השם יופיע בברכה במסך הבית.",
  enableBiometric: "הפעלת כניסה ביומטרית",
  inviteFine: "בלי סיסמה: הכניסה עם Face ID או טביעת אצבע.\nמפתח הגישה נשמר מוצפן בטלפון ומגובה בחשבון Apple או Google שלך.",
  allSet: (name: string) => `הכל מוכן, ${name}!`,
  allSetSub: "מעכשיו נכנסים עם Face ID או טביעת אצבע.",
  toCashflow: (month: string) => `לתזרים של ${t.monthName(month)}`,
  biometricSub: "נכנסים בלי סיסמה, עם זיהוי ביומטרי.",
  loginFaceId: "כניסה עם Face ID",
  loginFingerprint: "כניסה עם טביעת אצבע",
  newPhone: "טלפון חדש? מי שהתקין/ה את האפליקציה יכול/ה ליצור הזמנה חדשה.",
  googleSub: "נכנסים עם חשבון Google.",
  continueWithGoogle: "המשך עם Google",
  onlySetUpAccounts: "רק החשבונות שהוגדרו בהתקנה יכולים להיכנס.",
  almostThere: "עוד רגע מתחילים",
  nameSub: "ככה נקרא לך באפליקציה. אפשר לשנות.",
  whatToCallYou: "איך לקרוא לך?",
  signedInWithGoogle: "מחובר/ת עם Google",
  signedInWithEmail: "מחובר/ת עם מייל",
  continue: "המשך",
  noAccessTitle: "לחשבון הזה אין גישה",
  noAccessSub: "רק החשבונות שהוגדרו בהתקנה יכולים להיכנס.",
  otherAccount: "כניסה עם חשבון אחר",
  needAccess: "צריך גישה? מי שהתקין/ה את האפליקציה יכול/ה להוסיף אותך.",
  emailSub: "נשלח לך קוד כניסה במייל.",
  emailLabel: "כתובת המייל",
  sendCode: "שליחת קוד",
  onlySetUpEmails: "רק כתובות המייל שהוגדרו בהתקנה מקבלות קוד.",
  checkEmail: "בדקו את המייל",
  codeSentTo: "שלחנו קוד ל-",
  login: "כניסה",
  resendCode: "לשלוח קוד חדש",
  codeFine: "הקוד בתוקף ל-10 דקות. לא הגיע? כדאי לבדוק בתיקיית הספאם.",
  wrongCode: "הקוד לא נכון או שפג תוקפו.",
  inviteInvalid: "ההזמנה כבר לא בתוקף",
  inviteInvalidSub: "כל הזמנה פועלת פעם אחת ותקפה 24 שעות.\nאפשר לבקש ממי שהתקין/ה את האפליקציה הזמנה חדשה.",
  alreadyHaveAccess: "כבר יש לך גישה מהטלפון הזה?",
  tooMany: "יותר מדי ניסיונות. כדאי לנסות שוב בעוד כמה דקות.",
  genericError: "משהו השתבש. כדאי לנסות שוב.",
  loadFailed: "לא הצלחנו לטעון את הנתונים.",
  retry: "לנסות שוב",

  accessFor: (names: string[]) => `יש גישה ל${names.join(" ול")}`,
  lastSync: (when: string) => `עודכן מ-RiseUp ${when}`,
  tokenValidUntil: (date: string) => `הטוקן בתוקף עד ${date}`,
  logout: "התנתקות",

  installTitle: "להוסיף למסך הבית?",
  installBody: "ככה האפליקציה תיפתח מאיקון, במסך מלא.",
  installIos: 'באייפון: לוחצים על שיתוף ואז על "הוסף למסך הבית".',
  install: "התקנה",
  notNow: "לא עכשיו",

  tokenExpiring: (days: number) => `החיבור ל-RiseUp יפוג בעוד ${days === 1 ? "יום אחד" : `${days} ימים`}`,
  tokenExpiringSub: "כדי שהנתונים ימשיכו להתעדכן, צריך לחדש את הטוקן.",
  tokenExpired: (date: string) => `הנתונים לא מתעדכנים מאז ${date}`,
  tokenExpiredSub: "הטוקן של RiseUp פג. אחרי החידוש הכל יתעדכן מיד.",
  renew: "לחידוש",
  renewTitle: "חידוש החיבור ל-RiseUp",
  renewHow: "ככה מחדשים, פעם ב-30 יום:",
  renewStep1: "נכנסים ל-RiseUp ופותחים את עמוד הטוקנים למפתחים.",
  renewStep2: "יוצרים טוקן חדש עם הרשאת קריאה (budget:read).",
  renewStep3: "מעתיקים אותו ומדביקים כאן.",
  newToken: "הטוקן החדש",
  tokenHelp: "הטוקן נשמר מוצפן בחשבון שלכם בלבד, ולא מוצג שוב.",
  saveAndSync: "שמירה ועדכון הנתונים",
  tokenRejected: "RiseUp לא קיבלו את הטוקן. אולי פג תוקפו: כדאי ליצור טוקן חדש ולהדביק אותו.",
  tokenMalformed: "זה לא נראה כמו טוקן שלם. כדאי להעתיק אותו שוב, בלי רווחים ובלי שורות.",
  tokenSaved: "הטוקן עודכן. הנתונים מתעדכנים.",
  currentTokenUntil: (date: string) => `הטוקן הנוכחי בתוקף עד ${date}`,
  noBudgetYet: "עוד אין נתונים לחודש הזה.",
  loading: "טוען…",
};
